sudo: false
language: node_js
notifications:
  email: false
node_js:
  - 'stable'
before_script:
  - npm install -g istanbul
  - npm run-script pretest
script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly --
after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
